### ISSUE TITLE
Use with hogan

### ISSUE THREAD

**Issue by cjroebuck** [mklabs/templatify#1]
How would I replace handlebars with hogan

**Comment by mklabs** [comment]
Hi @cjroebuck 

That's a really good question. I really need to flesh out the documentation on adapters but I tried to decouple the middleware code from actual template engine implementation as much as possible.

It still a little bit clumpsy but it works pretty well. Hopefully, hogan adapters won't be too hard to implement, it seems like its api and featureset is pretty close to handlerbars. It even has a scanner / parser so that introspection may be implemented as well.

I'll probably work on this today, at least putting a decent documentation on how to create custom adapters.

**Comment by mklabs** [comment]
@cjroebuck I have a [good start](https://github.com/mklabs/templatify/commit/555132a7b2f8b2678726eeaafb5ae0c40feee3fc) on an hogan adapter, check out the [hogan](https://github.com/mklabs/templatify/tree/hogan) branch.

Usage would be as follow:

```
var b = browserify()
  .use(templatify('./', {
    files: ['**/*.html'],
    adapter: templatify.adapters.hogan
  }));

console.log(b.bundle());
```

**Comment by cjroebuck** [comment]
This is awesome, thanks! 

I'm really close to getting it working as I want, one little niggle I have come across is that I need to add each path to my templates into the `ignore` config option to browserify otherwise it tries to require it in at startup. 

Say I have a template defined at `app/client/templates/myTemplate.html`, and I have `require('app/client/templates/myTemplate')` within my view (at `app/client/views/MyView`)  I then need to add the path `app/client/templates/myTemplate` into browserify's ignore option, otherwise I get the following error at startup:

```
[ERROR] Error
Error: Cannot find module "app/client/templates/myTemplate" from directory    "/Users/cjroebuck/Dev/app/client/views"
at EventEmitter.require (/Users/cjroebuck/Dev/node_modules/browserify/lib/wrap.js:363:19)
at /Users/cjroebuck/Dev/node_modules/browserify/lib/wrap.js:441:14
at Array.forEach (native)
at EventEmitter.require (/Users/cjroebuck/Dev/node_modules/browserify/lib/wrap.js:440:27)
at /Users/cjroebuck/Dev/node_modules/browserify/lib/wrap.js:441:14
at Array.forEach (native)
at EventEmitter.require (/Users/cjroebuck/Dev/node_modules/browserify/lib/wrap.js:440:27)
at /Users/cjroebuck/Dev/node_modules/browserify/lib/wrap.js:441:14
at Array.forEach (native)
at EventEmitter.require (/Users/cjroebuck/Dev/node_modules/browserify/lib/wrap.js:440:27)
```

Have you come across this issue before? Is there any way to resolve it other than having to put each path to the template in the ignore option of browserify?

Thanks again - much appreciated.

**Comment by mklabs** [comment]
Hmm, I did have this issue before and I thought I solved it with [these few lines](https://github.com/mklabs/templatify/blob/hogan/lib/middleware.js#L100-106). Can you check the `ign` values by logging it and see if it has `app/client/templates/myTemplate` value in it.

I'll check this out and add some tests for this case, there's nothing testing it with a whole browserify package.

Other than that, if it's working for you then great :)

**Comment by mklabs** [comment]
Added a very basic test, unfortunately I couldn't reproduce your issue. Can you detail your process? Are you using the `bundle.addEntry` method from browserify after templatify middleware like [it's done here](https://github.com/mklabs/templatify/blob/47502c83c99da3ec4998a955d3b54dfbc3009bcb/test/bro.js#L21-31) ?

The ignore done from within the middleware seems to work on this simple test case, if I comment out the `b.ignore` I do get this nasty error. But maybe your environment is a bit different.

**Comment by cjroebuck** [comment]
Ah I see what you did there,  I am using the `require` option on browserify config to do the same thing. I will try using `addEntry`, and put the require in a file there.

I think its an ordering issue, as the `ign` field is populated when I remove the require option, however when I add the require option back, I get the error before templatify has a chance to initialise.

**Comment by cjroebuck** [comment]
Ok so now I have the opposite problem, the files/modules I was putting in my `ignore` config are now not being ignored. 

It looks as if calling `ignore` the second time overwrites what was in their originally.

**Comment by cjroebuck** [comment]
Hmm, Seems the only way I can get this to work is by modifying browserifys ignore method:

```
Wrap.prototype.ignore = function (files) {
if (!files) files = [];
if (!Array.isArray(files)) files = [ files ];

that = this;
files.forEach(function(f) {
    that.ignoring[f] = true;
});

// this.ignoring = files.reduce(function (acc,x) {
//     acc[x] = true;
//     return acc;
// }, {});

return this;
};
```

This just means browserify doesn't overwrite the previous ignored files.

**Comment by mklabs** [comment]
Thanks for all the feedback.

I'll let this issue open, we shouldn't have to make this dance to make it work. It should work with `bundle.addEntry` and `bundle.require`. If you can (if not it's okay too), it'd be great to put a simple gist to demonstrate your use case and the steps to reproduce the problem. I'll add this to the tests coverage.
